### ISSUE TITLE
Unable to open new Notes doc in MacOS after adding basic attachments code

### ISSUE THREAD

**Issue by bjax** [thesecretlab/LearningSwift1Ed#1]
I've checked several times and compared to code in this repository, but I'm unable to open a new Notes document in MacOS 10.11 after completing all the steps up to, but not including, "Enhancing Attachments" in Chapter 6 of the Preview version eBook.

An error is encountered just after `windowNibName` is called:

```
2016-04-02 10:26:24.102 Notes[49301:2552284] *** Assertion failure in -[NSCollectionView setItemPrototype:], /Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1404.46/Binding.subproj/NSCollectionView.m:1286
2016-04-02 10:26:24.103 Notes[49301:2552284] Use -registerNib:forItemWithIdentifier: and -registerClass:forItemWithIdentifier: with new CollectionViews
```

Is this a possible mis-configuration in one of the many `.xib` settings? I tried twice to create the user interface resources by carefully following steps to this point in the book.

I know the code in this repo represents the final version of the MacOS Notes app, but all the snippets described in the eBook up to page 154 appear to match my version.

I'm using XCode 7.3 with MacOS X 10.11.4.

I'll edit this if anything changes after proceeding to later steps in Chapter 6.

**Comment by bjax** [comment]
I've also compared my `.xib` objects XML for both `AddAttachmentViewController.xib` and `AttachmentCell.xib` against the final version from this repository and, aside from different values for tool versions, constraints, locations, ids, etc. see no structural differences.

**Comment by bjax** [comment]
Found the problem in Document.xib (comparing in a text editor with the book's version): somehow an additional outlet with an `itemPrototype` property got added to the main document window, likely a slip of the control-dragging finger.

Thanks for a pretty nice book!

**Comment by sldaedalus** [comment]
Cool! I'm glad that your issue was resolved.

Also: thank you very much indeed for such a well written initial issue. I got to the thread after you'd reported it fixed, but your notes were a great start to me to start figuring out the problem.
